#!/usr/bin/python3

import sys, os, os.path
import hashlib
import pyalpm

BUFSIZE = 65536

allpaths = set()

def errprint(s):
    print(s, file=sys.stderr)

h = pyalpm.Handle('/', '/var/lib/pacman')
db = h.get_localdb()
for pkg in db.pkgcache:
    for path, db_md5 in pkg.backup:
        path = '/' + path
        md5 = hashlib.md5()
        try:
            with open(path, 'rb', BUFSIZE) as f:
                for chunk in iter(lambda: f.read(BUFSIZE), b''):
                    md5.update(chunk)
        except FileNotFoundError:
            for p, _, _ in pkg.files:
                if path == '/' + p:
                    errprint('{} MISSING ({})'.format(path, pkg.name))
                    break
        except PermissionError as e:
            errprint('{} ({})'.format(e, pkg.name))
        else:
            if md5.hexdigest() != db_md5:
                print(path)
    for path, _, _ in pkg.files:
        allpaths.add('/' + path)

for top in ('/etc', '/usr/local/etc'):
    for dirpath, dirnames, filenames in os.walk(top, onerror=errprint):
        for fn in filenames:
            path = os.path.join(dirpath, fn)
            if path not in allpaths:
                print(path)
